- name: installing and configring the backend
  hosts: backend
  become: yes
  tasks:
    - name: disabling default nodejs
      ansible.builtin.command: dnf module disable nodejs -y

    - name: enabling the node js:20
      ansible.builtin.command: dnf module enable nodejs:20 -y

    - name: installing nodes js
      ansible.builtin.dnf:
        name: nodejs
        state: installed

    - name: creating user
      ansible.builtin.user:
        name: expense

    - name: creating /app directory
      ansible.builtin.file:
        path: /app
        state: directory

    - name: downloding the backend code
      ansible.builtin.get_url:
        url: https://expense-builds.s3.us-east-1.amazonaws.com/expense-backend-v2.zip
        dest: /tmp/backend.zip
              
    - name: unzipping backend code
      ansible.builtin.unarchive:
        src: /tmp/backend.zip
        dest: /app
        remote_src: yes

    - name: installing npm dependices  
      ansible.builtin.command: npm install
      args:
        chdir: /app
    
    - name: copying the backend.service
      ansible.builtin.copy:
        src: /home/ec2-user/Ansible-Project
        dest: /etc/systemd/system/backend.service