- name: nginx installation and configireation with backend
  hosts: frontend
  become: yes
  tasks:
    - name: nginx install
      ansible.builtin.dnf:
        name: nginx
        state: installed
        
    - name: starting the nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
    
    - name: delete default website  
      ansible.builtin.file:
        path: /usr/share/nginx/html/
        state: absent
    