- name: nginx installation and configireation with backend
  hosts: frontend
  become: yes
  tasks:
    - name: nginx install
      ansible.builtin.dnf:
        name: nginx
        state: started
        enabled: yes